FROM mcr.microsoft.com/dotnet/sdk:10.0.301-resolute
RUN apt-get update ; apt-get install -y gcc lua5.5 liblua5.5
COPY --parents "**.csproj" "**.slnx" "**.props" "/source"
RUN dotnet restore "/source"
ENTRYPOINT cp -r "/source" "/work" ; dotnet test --verbosity normal -p:TestingPlatformShowTestsFailure=true "/work"
